name: 'Critical CSS'
description: 'Generate Critical CSS'
inputs:
    serverBaseUrl:
        description: 'The base url of the site'
        required: true
    destinationPath:
        description: 'The destination path to store the generated files'
        required: false
        default: './criticalcss/'
    configPath:
        description: 'Path to config file'
        required: true
    sync:
        description: 'Should the generated files be synced to the remote server'
        required: false
        default: 'true'
    sshPrivateKeyPath:
        description: 'Optional ssh options'
        required: false
        default: ''
    sshHost:
        description: 'The host to connect to in user@host format'
        required: true
    sshPort:
        description: 'The ssh port in string format'
        required: false
        default: '22'
    targetDir:
        description: 'Directory to store generated files'
        required: true

runs:
    using: 'node16'
    main: 'dist/index.js'
branding:
    icon: 'package'
    color: 'gray-dark'
